### ISSUE TITLE
Uncaught Error: while running Update Network

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-bwtrace#95]
I was tailing the PHP Error log while running update network on wp.a2z and saw the following appear twice. 
```
14-Jan-2021 16:46:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attempt_reset() on null in C:\apache\htdocs\wordpress\wp-content\plugins\oik-bwtrace\includes\class-BW-trace-controller.php:493
```

Stack trace:
```
#0 wp-content\plugins\oik-bwtrace\includes\oik-actions.php(754): BW_trace_controller->purge_trace_file_if_no_errors()
#1 wp-includes\class-wp-hook.php(287): bw_trace_purge_if_no_errors('')
#2 wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#4 wp-a2z\wp-includes\load.php(1052): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in wp-content\plugins\oik-bwtrace\includes\class-BW-trace-controller.php on line 493
```

**Comment by bobbingwide** [comment]
This issue is over 3 years old. I no longer use `wp.a2z`. 
Closing unless I can reproduce it on `s.b/bwcom` - which is also WordPress Multisite
